apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090   # koneksi antar-container tetap pakai port internal 9090
    isDefault: true
    editable: true
